server:
  port: 8888
  contextPath: /

spring:
  datasource:
#    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Mysql
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true

  h2.console.enabled: true

logging.level.org.hibernate.SQL: debug
