server:
  port: 8888
  contextPath: /

spring:
  profiles.active: mysql
  datasource:
#    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Mysql
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: false

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true

  h2.console.enabled: true

logging.level.org.hibernate.SQL: debug

---

spring:
  profiles: mysql
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://data.bookstorage.kr:3306/aws
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
